import * as Tone from 'tone';
import type { Edge } from '../performance/frame';
import {MODES,type MusicMode,type Rhythm} from './modes';
import {breakPatternIndex,clamp01,wobbleParameters} from './motion';
import {chordForDegree,melodicIndex,PROGRESSIONS,SCALES,type ProgressionName,type ScaleName} from './theory';

export type HarmonyName='maj7'|'sus'|'minadd9';
export type EdgeEvent={edge:Edge;zone:number;position:number;velocity:number;direction:'in'|'out'};
export function harmonyForPhase(phase:number,current?:HarmonyName):HarmonyName{const p=Math.abs(phase);if(current==='maj7'&&p<57)return current;if(current==='sus'&&p>33&&p<147)return current;if(current==='minadd9'&&p>123)return current;return p<45?'maj7':p>135?'minadd9':'sus'}
export function replaceScheduledEvent(previous:number|undefined,clear:(id:number)=>void,schedule:()=>number){if(previous!==undefined)clear(previous);return schedule()}

const JUNGLE_PATTERNS=[
  {kick:[0,10],snare:[4,12],hat:[2,6,14],ghost:[]},
  {kick:[0,7,10],snare:[4,12],hat:[2,6,9,14],ghost:[11]},
  {kick:[0,3,7,10,15],snare:[4,12],hat:[1,2,6,9,14],ghost:[5,11]},
  {kick:[0,3,7,9,10,15],snare:[4,12],hat:[1,2,5,6,9,13,14],ghost:[5,8,11,15]},
];

/** Tone.js orchestration is independent from camera/body input. */
export class MusicEngine{
  private limiter=new Tone.Limiter(-2).toDestination();private master=new Tone.Gain(.8).connect(this.limiter);
  private melodyGain=new Tone.Gain(.7).connect(this.master);private harmonyGain=new Tone.Gain(.45).connect(this.master);private bassGain=new Tone.Gain(.5).connect(this.master);private drumGain=new Tone.Gain(.55).connect(this.master);
  private delay=new Tone.FeedbackDelay({delayTime:'8n',feedback:.25,wet:1}).connect(this.master);private delaySend=new Tone.Gain(0).connect(this.delay);private reverb=new Tone.Reverb({decay:4,wet:1}).connect(this.master);private reverbSend=new Tone.Gain(.08).connect(this.reverb);
  private melody=new Tone.PolySynth(Tone.Synth).connect(this.melodyGain);private chords=[new Tone.PolySynth(Tone.Synth).connect(this.harmonyGain),new Tone.PolySynth(Tone.Synth).connect(this.harmonyGain)];
  private bass=new Tone.MonoSynth().connect(this.bassGain);private kick=new Tone.MembraneSynth().connect(this.drumGain);private noise=new Tone.NoiseSynth({volume:-14}).connect(this.drumGain);
  private texture=new Tone.NoiseSynth({volume:-22,envelope:{attack:1,release:3}}).connect(this.reverb);
  private wobbleGain=new Tone.Gain(.28).connect(this.bassGain);private wobbleDrive=new Tone.Distortion(.18).connect(this.wobbleGain);private wobble=new Tone.MonoSynth({oscillator:{type:'sawtooth'},filter:{type:'lowpass',Q:4,rolloff:-24},envelope:{attack:.03,decay:.2,sustain:.7,release:.25},filterEnvelope:{attack:.02,decay:.15,sustain:.4,release:.2,baseFrequency:100,octaves:3}}).connect(this.wobbleDrive);private wobbleLfo=new Tone.LFO({frequency:1,min:120,max:900}).connect(this.wobble.filter.frequency).start();
  private scheduled?:number;private chord?:HarmonyName;private chordKey='';private bank=0;private step=0;private enabled=false;private accompaniment=true;private wobbleActive=false;private junglePattern=0;
  mode:MusicMode='band';rhythm:Rhythm='8 beat';root='C';scale:ScaleName='major pentatonic';progression:ProgressionName='pop';experimental=false;quantize:'4n'|'8n'|'16n'|null='8n';bpm=100;
  constructor(){this.melody.connect(this.delaySend);this.melody.connect(this.reverbSend);this.chords.forEach(x=>x.connect(this.reverbSend))}
  async setEnabled(on:boolean){if(on){await Tone.start();Tone.getTransport().start()}this.enabled=on;this.master.gain.rampTo(on ? .8 : 0,.12);if(!on)this.stopVoices()}
  setMode(mode:MusicMode){this.stopPattern();this.stopVoices();this.resetEffects();this.mode=mode;const config=MODES[mode];this.rhythm=config.rhythm;this.quantize=config.quantize;this.progression=mode==='ambient'?'ambient':mode==='dub'?'dub':'pop';const oscillator=mode==='techno'||mode==='dubstep'?'sawtooth':mode==='dub'?'square':'sine';this.melody.set({oscillator:{type:oscillator}});this.delaySend.gain.rampTo(mode==='dub'?.3:0,.25);this.reverbSend.gain.rampTo(mode==='ambient'?.45:.08,.35);this.setTempo(config.bpm);this.restartPattern()}
  setTempo(bpm:number){this.bpm=Math.round(Math.max(40,Math.min(180,bpm)));Tone.getTransport().bpm.rampTo(this.bpm,2)}
  setAccompaniment(on:boolean){this.accompaniment=on;this.restartPattern()}
  setRhythm(rhythm:Rhythm){this.rhythm=rhythm;this.restartPattern()}
  setVolumes(master:number,melody:number,harmony:number){this.master.gain.rampTo(clamp01(master),.1);this.melodyGain.gain.rampTo(clamp01(melody),.1);this.harmonyGain.gain.rampTo(clamp01(harmony),.1)}
  setGestureControl(value:number){const amount=clamp01(value);if(this.mode==='dubstep'){const params=wobbleParameters(amount);this.wobbleLfo.frequency.rampTo(params.lfoHz,.12);this.wobbleLfo.min=Math.max(80,params.cutoff*.28);this.wobbleLfo.max=params.cutoff;this.wobble.filter.Q.rampTo(params.resonance,.15);this.wobbleDrive.distortion=.12+amount*.28;if(this.enabled&&!this.wobbleActive){this.wobble.triggerAttack(this.noteFromSemitone(-24),undefined,.32);this.wobbleActive=true}}else if(this.mode==='jungle')this.junglePattern=breakPatternIndex(amount)}
  get activePatternCount(){return this.scheduled===undefined?0:1}
  private stopPattern(){if(this.scheduled!==undefined){Tone.getTransport().clear(this.scheduled);this.scheduled=undefined}}
  private restartPattern(){if(!this.accompaniment||this.rhythm==='free time'){this.stopPattern();return}this.step=0;const transport=Tone.getTransport();this.scheduled=replaceScheduledEvent(this.scheduled,id=>transport.clear(id),()=>transport.scheduleRepeat((time:number)=>this.tick(time),this.mode==='jungle'?'16n':'8n'))}
  private tick(time:number){if(!this.enabled)return;if(this.mode==='jungle'){const beat=this.step%16,pattern=JUNGLE_PATTERNS[this.junglePattern];if(pattern.kick.includes(beat))this.kick.triggerAttackRelease('C1','16n',time,.55);if(pattern.snare.includes(beat))this.noise.triggerAttackRelease('16n',time,.42);if(pattern.hat.includes(beat))this.noise.triggerAttackRelease('64n',time,.13);if(pattern.ghost.includes(beat))this.noise.triggerAttackRelease('64n',time,.08);if(beat%8===0)this.bass.triggerAttackRelease(this.noteFromSemitone(-24),'8n',time,.3);this.step++;return}const beat=this.step%8,even=this.step%2===0;if(this.mode==='dubstep'){if(beat===0||beat===5)this.kick.triggerAttackRelease('C1','8n',time,.65);if(beat===4)this.noise.triggerAttackRelease('8n',time,.45);if(beat===0)this.bass.triggerAttackRelease(this.noteFromSemitone(-24),'4n',time,.42);this.step++;return}if((this.mode==='techno'&&even)||(this.mode==='band'&&beat%4===0)||(this.mode==='dub'&&(beat===0||beat===5)))this.kick.triggerAttackRelease('C1','8n',time,.6);if((this.mode==='techno'&&!even)||(this.mode==='band'&&(beat===2||beat===6))||(this.mode==='dub'&&beat===4))this.noise.triggerAttackRelease('16n',time,.25);if(even&&this.mode!=='ambient'){const degree=PROGRESSIONS[this.progression][Math.floor(this.step/8)%PROGRESSIONS[this.progression].length];this.bass.triggerAttackRelease(this.noteFromSemitone(SCALES[this.scale][degree%SCALES[this.scale].length]-12),'8n',time,.35)}this.step++}
  private eventTime(){return this.quantize?Tone.getTransport().nextSubdivision(this.quantize):undefined}
  private noteFromSemitone(semitone:number,octave=4){return Tone.Frequency(Tone.Frequency(this.root+octave).toMidi()+semitone,'midi').toNote()}
  note(index:number){return this.noteFromSemitone(SCALES[this.scale][index%SCALES[this.scale].length]+12*Math.floor(index/SCALES[this.scale].length),3)}
  handleEdge(event:EdgeEvent){if(!this.enabled)return'';const time=this.eventTime(),v=Math.min(.85,.22+event.velocity),degree=PROGRESSIONS[this.progression][Math.floor(this.step/8)%PROGRESSIONS[this.progression].length];if(this.mode==='dubstep'&&event.edge==='right'){this.setGestureControl(event.position);return'WOBBLE'}if(this.mode==='jungle'&&event.edge==='right'){this.junglePattern=(this.junglePattern+1)%4;return'BREAK '+(this.junglePattern+1)}if(event.edge==='bottom'){this.kick.triggerAttackRelease('C1','8n',time,v);const note=this.noteFromSemitone(melodicIndex(this.scale,degree,event.zone,this.experimental)-24);this.bass.triggerAttackRelease(note,this.mode==='dubstep'?'4n':'8n',time,v);return note}if(event.edge==='left'){this.noise.triggerAttackRelease(event.zone%2?'32n':'16n',time,v);if(this.mode==='ambient')this.texture.triggerAttackRelease(.8,time,v);return this.mode==='jungle'?'GHOST':'PERC'}if(event.edge==='right'){if(this.mode==='dub'){this.delay.feedback.rampTo(Math.min(.62,.18+event.zone*.07),.2);return'DELAY'}const chord=chordForDegree(this.scale,degree,this.experimental).map(x=>this.noteFromSemitone(x));this.melody.triggerAttackRelease(chord,'8n',time,v);return'CHORD'}const semitone=melodicIndex(this.scale,degree,event.zone+8,this.experimental),note=this.noteFromSemitone(semitone);this.melody.triggerAttackRelease(note,this.mode==='ambient'?'2n':this.mode==='jungle'?'32n':'8n',time,v);return note}
  setContinuous(edge:Edge,proximity:number,position:number){if(!this.enabled)return;if(this.mode==='ambient')this.reverbSend.gain.rampTo(.1+proximity*.55,.4);if(this.mode==='dub'&&edge==='right'){this.delaySend.gain.rampTo(proximity*.7,.25);this.delay.feedback.rampTo(Math.min(.62,.15+position*.45),.25)}if(this.mode==='dubstep'&&edge==='right')this.setGestureControl(position)}
  setCoordination(phase:number,stability:number,on=true){if(!this.enabled||!on)return;const name=harmonyForPhase(phase,this.chord),degree=PROGRESSIONS[this.progression][Math.floor(this.step/8)%PROGRESSIONS[this.progression].length],intervals=name==='maj7'?[0,4,7,11]:name==='sus'?[0,5,7,10]:[0,3,7,14],inversion=this.mode==='band'?Math.round(Math.abs(phase)/90):0,notes=intervals.map((n,i)=>this.noteFromSemitone(n+(i<inversion?12:0),3)),key=name+degree+this.root+this.mode;if(key!==this.chordKey){this.chords[this.bank].releaseAll(Tone.now()+.25);this.bank=1-this.bank;this.chords[this.bank].triggerAttack(notes,Tone.now()+.04,.28);this.chordKey=key;this.chord=name}const tension=1-stability;if(this.mode==='ambient')this.reverbSend.gain.rampTo(.2+tension*.5,.5);else if(this.mode==='techno')this.harmonyGain.gain.rampTo(.35+tension*.2,.4);else if(this.mode==='dub')this.delaySend.gain.rampTo(tension*.45,.4)}
  get harmonyName(){return this.chord?.toUpperCase()??'UNAVAILABLE'}
  dispose(){this.stopPattern();this.stopVoices();this.wobbleLfo.stop()}
  private resetEffects(){this.delaySend.gain.rampTo(0,.08);this.reverbSend.gain.rampTo(.08,.08);this.delay.feedback.rampTo(.25,.08);this.wobbleDrive.distortion=.18}
  stopVoices(){this.melody.releaseAll();this.chords.forEach(x=>x.releaseAll());this.bass.triggerRelease();this.texture.triggerRelease();this.wobble.triggerRelease();this.wobbleActive=false;this.chordKey='';this.chord=undefined}
}

export{MusicEngine as Music};
