import './style.css';
import {Hands,type Hand} from './tracking/hands';
import {analyze,jointAngle,type Sample} from './analysis/coordination';
import {MusicEngine} from './music/engine';
import {MODES,modeNames,type MusicMode} from './music/modes';
import type {ProgressionName,ScaleName} from './music/theory';
import {bodyTempo,reconcileTempo,weatherTempo,type TempoSource} from './music/tempo';
import {BreakControl,handDistance,SmoothedControl} from './music/motion';
import {StableColor,colorFamily,rgbToHsv} from './input/color';
import {CameraSession,displayPointForCamera} from './input/camera';
import {MicrophoneTempoInput} from './input/microphone';
import {CrossingTracker,insideFrame,type Crossing,type Edge,type Frame,type Point} from './performance/frame';
import {DEFAULT_FRAME,DEFAULT_FIELD_SETTINGS,loadFieldSettings,ContactTracker,frameFromPoints,clampSegments} from './performance/settings';
import {NodDetector} from './input/nod';
import {FaceTracker} from './tracking/face';

type PlayMode='crossing'|'free'|'hybrid';type Side='Left'|'Right';
const app=document.querySelector<HTMLDivElement>('#app')!;
const options=(values:string[])=>values.map(x=>`<option value="${x}">${x.toUpperCase()}</option>`).join('');
app.innerHTML=`<main><header class="statusbar"><span id="camera-status">CAMERA: IDLE</span><span id="tracking-status">TRACKING: IDLE</span><span id="audio-status">AUDIO: OFF</span></header>
<nav id="modes" aria-label="Music mode">${modeNames.map(x=>`<button data-mode="${x}">${MODES[x].label}</button>`).join('')}</nav>
<section class="stage" data-mode="band"><video id="video" playsinline muted></video><canvas id="canvas"></canvas><div class="stage-label">MAIN STAGE <span>CAMERA / DEMO POINTER</span></div><div id="area"><b>PERFORMANCE FIELD</b>${(['top','right','bottom','left'] as Edge[]).map(x=>`<div class="edge ${x}"><em></em></div>`).join('')}<i data-handle="nw"></i><i data-handle="ne"></i><i data-handle="sw"></i><i data-handle="se"></i></div><button id="start" class="primary">START CAMERA</button><button id="panel-toggle">CONTROLS</button></section>
<section id="readouts"><article><small>LEFT INDEX</small><strong id="left-angle">—</strong><em>flex angle</em></article><article><small>RELATIVE PHASE</small><strong id="phase">UNAVAILABLE</strong><em id="stability">COORDINATION R —</em></article><article><small>RIGHT INDEX</small><strong id="right-angle">—</strong><em>flex angle</em></article><article><small>HARMONY</small><strong id="harmony">UNAVAILABLE</strong><em id="current-note">NOTE —</em></article><article><small>CURRENT BPM</small><strong id="current-bpm">100</strong><em id="input-confidence">MANUAL</em></article><article><small id="gesture-label">BODY CONTROL</small><strong id="gesture-value">—</strong><em id="gesture-detail">SELECT DUBSTEP / JUNGLE</em></article><article><small>10 SECOND MOTION</small><canvas id="graph"></canvas><em>LEFT / RIGHT</em></article></section>
<aside id="controls"><section><h2>MUSIC SETTINGS</h2><div class="button-row"><button id="audio">AUDIO ON</button><button id="auto">AUTO ACCOMPANIMENT ON</button></div><label>Frame performance<select id="play-mode">${options(['crossing','free','hybrid'])}</select></label><label>Rhythm<select id="rhythm"></select></label><label>Quantize<select id="quantize">${options(['off','4n','8n','16n'])}</select></label><label>Key<select id="root">${options(['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'])}</select></label><label>Scale<select id="scale">${options(['major','natural minor','major pentatonic','minor pentatonic','dorian','mixolydian'])}</select></label><label>Chord progression<select id="progression">${options(['pop','jazz','ambient','dub'])}</select></label><button id="experimental">EXPERIMENTAL OFF</button><button id="theremin">THEREMIN OFF</button><p id="theremin-readout">THEREMIN: CENTER DISTANCE → PITCH · HORIZONTAL → VOLUME</p><label>Master volume<input id="master" type="range" min="0" max="1" step=".01" value=".8"></label><label>Melody volume<input id="melody-volume" type="range" min="0" max="1" step=".01" value=".7"></label><label>Harmony volume<input id="harmony-volume" type="range" min="0" max="1" step=".01" value=".45"></label></section>
<section><h2>INPUT SOURCE</h2><label>Tempo source<select id="tempo-source">${options(['manual','body','mic','weather'])}</select></label><label>BPM<input id="bpm" type="range" min="40" max="180" value="100"><output>100</output></label><p id="weather-rule">WEATHER: 55 + WIND KM/H × 2.25 (55–145 BPM)</p><div class="button-row"><button id="color">COLOR TO MUSIC OFF</button><button id="color-lock">COLOR LOCK OFF</button></div><p id="detected-color">COLOR —</p></section>
<section><h2>PERFORMANCE FIELD</h2><div class="button-row"><button id="default-frame">DEFAULT FRAME</button><button id="hand-frame">HAND FRAME OFF</button></div><p id="frame-status" aria-live="polite">FRAME: DEFAULT</p><label>CONTACT DISTANCE<input id="contact-distance" type="range" min="0.005" max="0.08" step="0.005" value="0.02"><output>0.020</output></label><label>CONTACT TIME<input id="contact-time" type="range" min="0" max="600" step="25" value="100"><output>100ms</output></label><label>EDGE SEGMENTS<input id="edge-segments" type="range" min="1" max="8" step="1" value="6"><output>6</output></label></section><section><h2>COORDINATION</h2><button id="coordination">MAPPING ON</button><label>Analysis window<input id="window" type="range" min="3" max="10" value="5"><output>5s</output></label></section>
<section><h2>DEMO MODE</h2><label>Simulation<select id="demo">${options(['off','0° in phase','90°','180° anti phase','variable','stop'])}</select></label><p>Drag or swipe across the frame to perform without a camera.</p></section>
<details><summary>DEBUG / FRAME</summary><label>Cooldown<input id="cooldown" type="range" min="40" max="500" value="120"><output>120ms</output></label><label>Minimum movement<input id="minimum" type="range" min=".001" max=".05" step=".001" value=".008"><output>.008</output></label><label>Hysteresis<input id="hysteresis" type="range" min="0" max=".04" step=".002" value=".008"><output>.008</output></label><div class="switches"><button id="edit">EDIT FRAME</button><button id="reset">RESET FRAME</button><button data-toggle="skeleton">SKELETON ON</button><button data-toggle="image">CAMERA ON</button><button id="stop">STOP CAMERA</button><button id="switch">SWITCH CAMERA</button><button id="fullscreen">FULLSCREEN</button><button id="hide-ui">HIDE UI</button></div></details><p class="privacy">All camera and microphone analysis stays in this browser. Coordination mappings are artistic, not assessments.</p></aside>
<footer><span id="fps">RENDER — FPS · TRACKING —</span><span>LEFT <b id="lh">OFF</b> / RIGHT <b id="rh">OFF</b></span></footer></main>`;
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;const video=$<HTMLVideoElement>('#video'),canvas=$<HTMLCanvasElement>('#canvas'),ctx=canvas.getContext('2d')!,graph=$<HTMLCanvasElement>('#graph'),gctx=graph.getContext('2d')!,stage=$('.stage'),area=$('#area');
const hands=new Hands(),music=new MusicEngine(),histories:Record<Side,Sample[]>={Left:[],Right:[]},trackers:Record<Side,CrossingTracker>={Left:new CrossingTracker({cooldownMs:120,minDistance:.008,hysteresis:.008}),Right:new CrossingTracker({cooldownMs:120,minDistance:.008,hysteresis:.008})};

function loadFrame():Frame{
  try{
    const saved=localStorage.getItem('finger-symphony-frame');
    if(!saved)return {...DEFAULT_FRAME};
    const value:unknown=JSON.parse(saved);
    if(typeof value!=='object'||value===null)return {...DEFAULT_FRAME};
    const candidate=value as Record<string,unknown>;
    const {x,y,width,height}=candidate;
    if(![x,y,width,height].every(v=>typeof v==='number'&&Number.isFinite(v)))return {...DEFAULT_FRAME};
    const f={x:x as number,y:y as number,width:width as number,height:height as number};
    if(f.width<0.2||f.height<0.2||f.x<0||f.y<0||f.x+f.width>1||f.y+f.height>1)return {...DEFAULT_FRAME};
    return f;
  }catch{return {...DEFAULT_FRAME}}
}
let fieldSettings=loadFieldSettings(),handFrame=false,frameLocked=false,handFramePoints:Point[]=[];
const contacts:Record<Side,ContactTracker>={Left:new ContactTracker(),Right:new ContactTracker()};
const nodDetector=new NodDetector(),faceTracker=new FaceTracker();
let frame:Frame=loadFrame(),mode:MusicMode='band',front=true,cameraVisible=true,skeleton=true,audio=false,auto=true,coordination=true,edit=false,demo='off',tempoSource:TempoSource='manual',animation=0,lastVideo=0,frames=0,fpsAt=0,trackingFrames=0,lastTrackingAt=0,recoveringTracking=false,thereminOn=false,colorOn=false,colorLock=false,lastColorAt=0;
const stableColor=new StableColor(),trails:{x:number;y:number;t:number;side:Side}[]=[],ripples:{x:number;y:number;t:number;side:Side}[]=[],freeZone:Record<Side,number|undefined>={Left:undefined,Right:undefined};
const tips:Partial<Record<Side,Point>>={};
const wobbleControl=new SmoothedControl(0,.15),jungleControl=new BreakControl();
const microphoneInput=new MicrophoneTempoInput();
const cameraSession=new CameraSession({video,requestStream:frontCamera=>navigator.mediaDevices.getUserMedia({video:{facingMode:frontCamera?'user':'environment',width:{ideal:1280},height:{ideal:720}},audio:false}),initializeTracking:()=>hands.init(),onReport:report=>{const message=report.message?' · '+report.message:'';$('#camera-status').textContent='CAMERA: '+report.camera+(report.camera==='ERROR'?message:'');$('#tracking-status').textContent='TRACKING: '+report.tracking+(report.tracking==='ERROR'?message:'')},onCameraReady:()=>{$('#start').hidden=true;startLoop()}});
function resize(){const d=devicePixelRatio;for(const c of [canvas,graph]){c.width=c.clientWidth*d;c.height=c.clientHeight*d}ctx.setTransform(d,0,0,d,0,0);gctx.setTransform(d,0,0,d,0,0);renderFrame()}addEventListener('resize',resize);
function renderFrame(){Object.assign(area.style,{left:frame.x*100+'%',top:frame.y*100+'%',width:frame.width*100+'%',height:frame.height*100+'%'});area.classList.toggle('editing',edit);(['top','right','bottom','left'] as Edge[]).forEach(edge=>{const node=$(`.edge.${edge}`);node.querySelector('em')!.textContent=MODES[mode].roles[edge];node.querySelectorAll('span').forEach(x=>x.remove());for(let i=0;i<fieldSettings.edgeSegments;i++)node.insertAdjacentHTML('beforeend','<span></span>')})}
function setMode(next:MusicMode){mode=next;music.setMode(next);wobbleControl.reset();jungleControl.reset();stage.dataset.mode=next;document.querySelectorAll('#modes button').forEach(x=>x.classList.toggle('active',(x as HTMLElement).dataset.mode===next));const cfg=MODES[next],rhythm=$<HTMLSelectElement>('#rhythm');rhythm.innerHTML=options(cfg.rhythms);rhythm.value=cfg.rhythm;$<HTMLInputElement>('#bpm').value=String(cfg.bpm);$('#bpm + output').textContent=String(cfg.bpm);$('#current-bpm').textContent=String(cfg.bpm);$<HTMLSelectElement>('#quantize').value=cfg.quantize??'off';$('#gesture-label').textContent=next==='dubstep'?'WOBBLE':next==='jungle'?'BREAK INTENSITY':'BODY CONTROL';$('#gesture-value').textContent=next==='dubstep'||next==='jungle'?'0%':'—';$('#gesture-detail').textContent=next==='dubstep'?'HAND DISTANCE':next==='jungle'?'HAND SPEED':'SELECT DUBSTEP / JUNGLE';renderFrame()}
async function setAudio(on:boolean){audio=on;await music.setEnabled(on);$('#audio').textContent='AUDIO '+(on?'OFF':'ON');$('#audio-status').textContent='AUDIO: '+(on?'ON':'OFF')}
function add(side:Side,angle:number,t:number){histories[side].push({t,angle});while(histories[side][0]?.t<t-10000)histories[side].shift()}
const displayPoint=(p:{x:number;y:number}):Point=>displayPointForCamera(p,front);
function proximity(point:Point){const distances:{edge:Edge,d:number,pos:number}[]=[{edge:'top',d:Math.abs(point.y-frame.y),pos:(point.x-frame.x)/frame.width},{edge:'bottom',d:Math.abs(point.y-frame.y-frame.height),pos:(point.x-frame.x)/frame.width},{edge:'left',d:Math.abs(point.x-frame.x),pos:(point.y-frame.y)/frame.height},{edge:'right',d:Math.abs(point.x-frame.x-frame.width),pos:(point.y-frame.y)/frame.height}];distances.sort((a,b)=>a.d-b.d);const n=distances[0];return{...n,amount:Math.max(0,1-n.d/.16)}}
function trigger(side:Side,crossing:Crossing,speed:number,direction:'in'|'out'){const zone=Math.min(fieldSettings.edgeSegments-1,Math.floor(crossing.position*fieldSettings.edgeSegments)),result=music.handleEdge({edge:crossing.edge,zone,velocity:Math.min(1,speed*5),direction});$('#current-note').textContent='NOTE '+result;const x=crossing.point.x*canvas.clientWidth,y=crossing.point.y*canvas.clientHeight;ripples.push({x,y,t:performance.now(),side});const segment=document.querySelector(`.edge.${crossing.edge} span:nth-of-type(${zone+1})`);segment?.classList.add('active');setTimeout(()=>segment?.classList.remove('active'),180)}
function perform(side:Side,point:Point,t:number){const tracker=trackers[side],previous=tracker.previous,crossings=tracker.updateAll(point,frame,t),speed=previous?Math.hypot(point.x-previous.x,point.y-previous.y):0,play=$<HTMLSelectElement>('#play-mode').value as PlayMode;if(mode==='jungle'){const control=jungleControl.update(speed,t);music.setGestureControl(control.pattern/3);$('#gesture-value').textContent=Math.round(control.value*100)+'%'}if(previous&&(play==='crossing'||play==='hybrid')){let isInside=insideFrame(previous,frame);crossings.forEach(crossing=>{trigger(side,crossing,speed,isInside?'out':'in');isInside=!isInside})}if(play==='crossing'||play==='hybrid'){for(const hit of contacts[side].update(point,frame,t,fieldSettings)){if(!crossings.some(c=>c.edge===hit.edge))trigger(side,hit,speed,'in')}}else contacts[side].reset();if(play==='free'||play==='hybrid'){const inside=insideFrame(point,frame),zone=inside?Math.max(0,Math.min(fieldSettings.edgeSegments-1,Math.floor((1-(point.y-frame.y)/frame.height)*fieldSettings.edgeSegments))):undefined;if(zone!==undefined&&zone!==freeZone[side]&&!crossings.length)music.handleEdge({edge:'top',zone,velocity:speed*5,direction:'in'});freeZone[side]=zone}const near=proximity(point);if(near.amount)music.setContinuous(near.edge,near.amount,Math.max(0,Math.min(1,near.pos)))}
function drawHand(hand:Hand,t:number){const color=hand.side==='Left'?'#68e8ff':'#ff54d7',points=hand.points.map(displayPoint),tip=points[8],x=tip.x*canvas.clientWidth,y=tip.y*canvas.clientHeight;tips[hand.side]=tip;if(handFrame&&!frameLocked){handFramePoints.push(points[4],points[8]);}if(thereminOn){const dx=tip.x-.5,dy=tip.y-.5,distance=Math.min(1,Math.hypot(dx,dy)/Math.SQRT1_2),volume=Math.min(1,Math.abs(tip.x-.5)*2);music.setTheremin(true,distance,volume);$('#theremin-readout').textContent=`THEREMIN: PITCH ${Math.round(distance*100)}% · VOLUME ${Math.round(volume*100)}%`}if(mode==='dubstep'&&tips.Left&&tips.Right){const amount=wobbleControl.update(handDistance(tips.Left,tips.Right));music.setGestureControl(amount);$('#gesture-value').textContent=Math.round(amount*100)+'%'}trails.push({x,y,t,side:hand.side});if(skeleton){ctx.strokeStyle=color;ctx.lineWidth=2;[[0,5,6,7,8],[0,9,10,11,12],[0,13,14,15,16],[0,17,18,19,20]].forEach(chain=>{ctx.beginPath();chain.forEach((n,i)=>i?ctx.lineTo(points[n].x*canvas.clientWidth,points[n].y*canvas.clientHeight):ctx.moveTo(points[n].x*canvas.clientWidth,points[n].y*canvas.clientHeight));ctx.stroke()})}const p=hand.points,angle=jointAngle([p[5].x,p[5].y,p[5].z],[p[6].x,p[6].y,p[6].z],[p[8].x,p[8].y,p[8].z]);add(hand.side,angle,t);$('#'+(hand.side==='Left'?'left':'right')+'-angle').textContent=angle.toFixed(0)+'°';perform(hand.side,tip,t)}
function simulate(t:number){if(demo==='off')return;const phase=demo.startsWith('90')?Math.PI/2:demo.startsWith('180')?Math.PI:demo==='variable'?t/1800:0,left=90+30*Math.sin(t/320),right=demo==='stop'?90:90+30*Math.sin(t/320+phase);add('Left',left,t);add('Right',right,t);$('#left-angle').textContent=left.toFixed(0)+'°';$('#right-angle').textContent=right.toFixed(0)+'°';if(mode==='dubstep'){const amount=wobbleControl.update((Math.sin(t/850)+1)/2);music.setGestureControl(amount);$('#gesture-value').textContent=Math.round(amount*100)+'%'}if(mode==='jungle'){const control=jungleControl.update((Math.sin(t/620)+1)/10,t);music.setGestureControl(control.pattern/3);$('#gesture-value').textContent=Math.round(control.value*100)+'%'}}
function draw(t:number){ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);while(trails[0]?.t<t-2000)trails.shift();trails.forEach(q=>{ctx.fillStyle=q.side==='Left'?'#68e8ff88':'#ff54d788';ctx.beginPath();ctx.arc(q.x,q.y,2,0,7);ctx.fill()});while(ripples[0]?.t<t-1200)ripples.shift();ripples.forEach(q=>{const age=(t-q.t)/1200;ctx.strokeStyle=(q.side==='Left'?'#68e8ff':'#ff54d7')+Math.round((1-age)*255).toString(16).padStart(2,'0');ctx.beginPath();ctx.arc(q.x,q.y,8+age*(mode==='dub'?65:40),0,7);ctx.stroke()})}
function drawGraph(){const w=graph.clientWidth,h=graph.clientHeight,end=Math.max(histories.Left.at(-1)?.t||0,histories.Right.at(-1)?.t||0);gctx.clearRect(0,0,w,h);(['Left','Right'] as Side[]).forEach(side=>{gctx.strokeStyle=side==='Left'?'#68e8ff':'#ff54d7';gctx.beginPath();histories[side].forEach((s,i)=>{const x=w-(end-s.t)/10000*w,y=h-s.angle/180*h;i?gctx.lineTo(x,y):gctx.moveTo(x,y)});gctx.stroke()})}
function sampleColor(t:number){if(!colorOn||colorLock||video.readyState<2||t-lastColorAt<500)return;lastColorAt=t;const c=document.createElement('canvas'),x=c.getContext('2d')!;c.width=20;c.height=20;x.drawImage(video,video.videoWidth/2-10,video.videoHeight/2-10,20,20,0,0,20,20);const data=x.getImageData(0,0,20,20).data;let r=0,g=0,b=0;for(let i=0;i<data.length;i+=4){r+=data[i];g+=data[i+1];b+=data[i+2]}const n=data.length/4,family=stableColor.update(colorFamily(rgbToHsv(r/n,g/n,b/n)));$('#detected-color').textContent='COLOR '+family.toUpperCase();if(family==='red')music.scale='major';if(family==='blue'||family==='purple')music.scale='dorian';if(family==='green')music.scale='major pentatonic'}
function loop(t:number){animation=0;let found:Hand[]=[];if(demo!=='off')simulate(t);else if(video.readyState>=2&&t!==lastVideo){lastVideo=t;try{const detected=hands.detect(video,t);if(detected){found=detected;trackingFrames++;lastTrackingAt=t;handFramePoints=[];found.forEach(x=>drawHand(x,t));if(handFrame&&!frameLocked&&handFramePoints.length===4){const candidate=frameFromPoints(handFramePoints);if(candidate){frame=candidate;renderFrame();$('#frame-status').textContent='FRAME: NOD TO LOCK'}}if(handFrame&&!frameLocked){const faceY=faceTracker.detect(video,t);if(faceY!==undefined&&nodDetector.update(faceY,t)){frameLocked=true;saveFrame();$('#frame-status').textContent='FRAME LOCKED'}}(['Left','Right'] as Side[]).forEach(side=>{if(!found.some(x=>x.side===side)){trackers[side].reset();freeZone[side]=undefined;delete tips[side]}})}}catch(error){console.error('Hand tracking failed',error);if(!recoveringTracking){recoveringTracking=true;$('#tracking-status').textContent='TRACKING: RECOVERING';void hands.recover().then(()=>{$('#tracking-status').textContent='TRACKING: READY'}).catch(recoveryError=>{console.error('Hand tracking recovery failed',recoveryError);$('#tracking-status').textContent='TRACKING: ERROR'}).finally(()=>{recoveringTracking=false})}}}const analysis=analyze(histories.Left,histories.Right,+$<HTMLInputElement>('#window').value*1000);$('#phase').textContent=analysis.available?Math.abs(analysis.phase).toFixed(0)+'°':'UNAVAILABLE';$('#stability').textContent=analysis.available?'COORDINATION R '+analysis.stability.toFixed(2):'COORDINATION R —';if(analysis.available){music.setCoordination(analysis.phase,analysis.stability,coordination);$('#harmony').textContent=music.harmonyName;if(tempoSource==='body'){const bpm=bodyTempo(histories.Left);if(bpm)updateTempo(reconcileTempo(bpm,music.bpm),'BODY')}}sampleColor(t);draw(t);drawGraph();$('#lh').textContent=found.some(x=>x.side==='Left')||demo!=='off'?'ON':'OFF';$('#rh').textContent=found.some(x=>x.side==='Right')||demo!=='off'?'ON':'OFF';frames++;if(t-fpsAt>1000){const tracking=demo!=='off'?'DEMO':recoveringTracking?'RECOVERING':lastTrackingAt&&t-lastTrackingAt>2000?'STALLED':trackingFrames+' FPS';$('#fps').textContent=`RENDER ${frames} FPS · TRACKING ${tracking} · ${hands.delegate}`;if(cameraSession.active&&demo==='off'&&lastTrackingAt&&t-lastTrackingAt>3000&&!recoveringTracking){recoveringTracking=true;$('#tracking-status').textContent='TRACKING: RECOVERING';void hands.recover().then(()=>{lastTrackingAt=performance.now();$('#tracking-status').textContent='TRACKING: READY'}).catch(error=>{console.error('Tracking watchdog recovery failed',error);$('#tracking-status').textContent='TRACKING: ERROR'}).finally(()=>{recoveringTracking=false})}fpsAt=t;frames=0;trackingFrames=0}if(cameraSession.active||demo!=='off'||ripples.length)animation=requestAnimationFrame(loop)}
function startLoop(){if(!animation)animation=requestAnimationFrame(loop)}function updateTempo(value:number,source:string){music.setTempo(value);$('#current-bpm').textContent=String(Math.round(value));$('#input-confidence').textContent=source}
async function weather(){try{const position=await new Promise<GeolocationPosition>((ok,no)=>navigator.geolocation.getCurrentPosition(ok,no,{timeout:8000})),{latitude,longitude}=position.coords,response=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=wind_speed_10m`),json=await response.json(),wind=Number(json.current.wind_speed_10m);updateTempo(weatherTempo(wind),`WEATHER ${wind} KM/H`)}catch{tempoSource='manual';$<HTMLSelectElement>('#tempo-source').value='manual';$('#input-confidence').textContent='WEATHER FAILED · MANUAL'}}
async function setTempoSource(next:TempoSource){await microphoneInput.stop();tempoSource=next;if(next==='weather')await weather();if(next==='mic')try{await microphoneInput.start(reading=>updateTempo(reconcileTempo(reading.bpm,music.bpm),`MIC ${Math.round(reading.confidence*100)}%`))}catch{tempoSource='manual';$<HTMLSelectElement>('#tempo-source').value='manual';$('#input-confidence').textContent='MIC DENIED · MANUAL'}else if(next==='manual')$('#input-confidence').textContent='MANUAL'}

document.querySelectorAll<HTMLButtonElement>('#modes button').forEach(x=>x.onclick=()=>setMode(x.dataset.mode as MusicMode));$('#audio').onclick=()=>setAudio(!audio);$('#auto').onclick=()=>{auto=!auto;music.setAccompaniment(auto);$('#auto').textContent='AUTO ACCOMPANIMENT '+(auto?'ON':'OFF')};$('#start').onclick=()=>void cameraSession.start(front);$('#stop').onclick=()=>{$('#start').hidden=false;cameraSession.stop();trackers.Left.reset();trackers.Right.reset();contacts.Left.reset();contacts.Right.reset();faceTracker.stop()};$('#switch').onclick=()=>{front=!front;if(cameraSession.active)void cameraSession.switchCamera(front);else cameraSession.setPresentation(cameraVisible,front)};$('#demo').onchange=e=>{demo=(e.target as HTMLSelectElement).value;histories.Left=[];histories.Right=[];trackers.Left.reset();trackers.Right.reset();if(demo!=='off')startLoop()};
$('#rhythm').onchange=e=>music.setRhythm((e.target as HTMLSelectElement).value as never);$('#quantize').onchange=e=>music.quantize=(e.target as HTMLSelectElement).value==='off'?null:(e.target as HTMLSelectElement).value as '4n'|'8n'|'16n';$('#root').onchange=e=>music.root=(e.target as HTMLSelectElement).value;$('#scale').onchange=e=>music.scale=(e.target as HTMLSelectElement).value as ScaleName;$('#progression').onchange=e=>music.progression=(e.target as HTMLSelectElement).value as ProgressionName;$('#experimental').onclick=()=>{music.experimental=!music.experimental;$('#experimental').textContent='EXPERIMENTAL '+(music.experimental?'ON':'OFF')};$('#theremin').onclick=()=>{thereminOn=!thereminOn;$('#theremin').textContent='THEREMIN '+(thereminOn?'ON':'OFF');if(!thereminOn){music.setTheremin(false);$('#theremin-readout').textContent='THEREMIN: CENTER DISTANCE → PITCH · HORIZONTAL → VOLUME'}};
function volumes(){music.setVolumes(+$<HTMLInputElement>('#master').value,+$<HTMLInputElement>('#melody-volume').value,+$<HTMLInputElement>('#harmony-volume').value)}['master','melody-volume','harmony-volume'].forEach(id=>$('#'+id).oninput=volumes);$('#bpm').oninput=e=>{const value=+(e.target as HTMLInputElement).value;$('#bpm + output').textContent=String(value);if(tempoSource==='manual')updateTempo(value,'MANUAL')};$('#tempo-source').onchange=e=>void setTempoSource((e.target as HTMLSelectElement).value as TempoSource);$('#coordination').onclick=()=>{coordination=!coordination;$('#coordination').textContent='MAPPING '+(coordination?'ON':'OFF')};$('#color').onclick=()=>{colorOn=!colorOn;$('#color').textContent='COLOR TO MUSIC '+(colorOn?'ON':'OFF')};$('#color-lock').onclick=()=>{colorLock=!colorLock;$('#color-lock').textContent='COLOR LOCK '+(colorLock?'ON':'OFF')};
(['cooldown','minimum','hysteresis'] as const).forEach(id=>$('#'+id).oninput=e=>{const value=+(e.target as HTMLInputElement).value,key=id==='cooldown'?'cooldownMs':id==='minimum'?'minDistance':'hysteresis';Object.values(trackers).forEach(x=>x.options[key]=value);$('#'+id+' + output').textContent=value+(id==='cooldown'?'ms':'')});$('#edit').onclick=()=>{edit=!edit;area.classList.toggle('editing',edit);$('#edit').textContent=edit?'DONE EDITING':'EDIT FRAME'};$('#reset').onclick=()=>{frame={...DEFAULT_FRAME};saveFrame()};$('#default-frame').onclick=()=>{handFrame=false;frameLocked=false;nodDetector.reset();frame={...DEFAULT_FRAME};$('#hand-frame').textContent='HAND FRAME OFF';$('#frame-status').textContent='FRAME: DEFAULT';saveFrame()};$('#hand-frame').onclick=()=>{handFrame=!handFrame;frameLocked=false;nodDetector.reset();$('#hand-frame').textContent='HAND FRAME '+(handFrame?'ON':'OFF');$('#frame-status').textContent=handFrame?'FRAME: SHOW FOUR FINGERTIPS':'FRAME: MANUAL';if(handFrame)void faceTracker.start().catch(e=>{$('#frame-status').textContent='FACE TRACKING ERROR';console.error(e)});else faceTracker.stop()};(['contact-distance','contact-time','edge-segments'] as const).forEach(id=>{const input=$<HTMLInputElement>('#'+id);const key=id==='contact-distance'?'contactDistance':id==='contact-time'?'contactTime':'edgeSegments';input.value=String(fieldSettings[key]);input.nextElementSibling!.textContent=id==='contact-distance'?fieldSettings.contactDistance.toFixed(3):id==='contact-time'?fieldSettings.contactTime+'ms':String(fieldSettings.edgeSegments);input.oninput=()=>{const value=Number(input.value);fieldSettings={...fieldSettings,[key]:key==='edgeSegments'?clampSegments(value):value};localStorage.setItem('finger-symphony-field-settings',JSON.stringify(fieldSettings));input.nextElementSibling!.textContent=key==='contactDistance'?value.toFixed(3):key==='contactTime'?value+'ms':String(value);contacts.Left.reset();contacts.Right.reset();renderFrame()}});document.querySelectorAll('[data-toggle]').forEach(x=>x.addEventListener('click',()=>{const key=(x as HTMLElement).dataset.toggle;if(key==='skeleton')skeleton=!skeleton;else{cameraVisible=!cameraVisible;cameraSession.setPresentation(cameraVisible,front)}x.textContent=(key==='skeleton'?'SKELETON ':'CAMERA ')+((key==='skeleton'?skeleton:cameraVisible)?'ON':'OFF')}));$('#fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();$('#hide-ui').onclick=()=>document.body.classList.toggle('hide-ui');$('#panel-toggle').onclick=()=>$('#controls').classList.toggle('open');
let drag:{kind:string,start:Point,original:Frame}|undefined;function pointer(e:PointerEvent):Point{const r=stage.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}area.onpointerdown=e=>{if(!edit)return;area.setPointerCapture(e.pointerId);drag={kind:(e.target as HTMLElement).dataset.handle||'move',start:pointer(e),original:{...frame}}};area.onpointermove=e=>{if(!drag)return;const p=pointer(e),dx=p.x-drag.start.x,dy=p.y-drag.start.y,o=drag.original;if(drag.kind==='move')frame={...o,x:o.x+dx,y:o.y+dy};else{const w=drag.kind.includes('w'),n=drag.kind.includes('n');frame={x:w?o.x+dx:o.x,y:n?o.y+dy:o.y,width:w?o.width-dx:o.width+dx,height:n?o.height-dy:o.height+dy}}frame.width=Math.max(.2,Math.min(.95,frame.width));frame.height=Math.max(.2,Math.min(.95,frame.height));frame.x=Math.max(0,Math.min(1-frame.width,frame.x));frame.y=Math.max(0,Math.min(1-frame.height,frame.y));renderFrame()};area.onpointerup=()=>{drag=undefined;saveFrame()};function saveFrame(){localStorage.setItem('finger-symphony-frame',JSON.stringify(frame));renderFrame();trackers.Left.reset();trackers.Right.reset();contacts.Left.reset();contacts.Right.reset()}
let demoPointer=false;stage.addEventListener('pointerdown',e=>{if(edit||demo==='off')return;demoPointer=true;stage.setPointerCapture(e.pointerId);const p=pointer(e);trackers.Left.reset();perform('Left',p,performance.now());startLoop()});stage.addEventListener('pointermove',e=>{if(!demoPointer)return;const p=pointer(e),t=performance.now();trails.push({x:p.x*canvas.clientWidth,y:p.y*canvas.clientHeight,t,side:'Left'});perform('Left',p,t)});stage.addEventListener('pointerup',()=>{demoPointer=false;trackers.Left.reset()});
resize();setMode('band');cameraSession.setPresentation(cameraVisible,front);
