import{describe,expect,it,vi}from'vitest';import{CameraSession,displayPointForCamera,type CameraReport}from'./camera';
const setup=(initializeTracking=vi.fn(async()=>{}),request=vi.fn(async()=>stream()))=>{const reports:CameraReport[]=[],video={hidden:false,classList:{toggle:vi.fn()},srcObject:null,play:vi.fn(async()=>{}),pause:vi.fn()} as unknown as HTMLVideoElement,ready=vi.fn(),session=new CameraSession({video,requestStream:request,initializeTracking,onReport:r=>reports.push(r),onCameraReady:ready});return{session,video,reports,ready,request,initializeTracking}};
const stream=()=>({getTracks:()=>[{stop:vi.fn()}]}) as unknown as MediaStream;
describe('camera input',()=>{
  it('matches mirrored preview coordinates',()=>{expect(displayPointForCamera({x:.2,y:.4},true)).toEqual({x:.8,y:.4});expect(displayPointForCamera({x:.2,y:.4},false)).toEqual({x:.2,y:.4})});
  it('shows camera before tracking finishes and reports both ready states',async()=>{let release!:()=>void;const tracking=new Promise<void>(ok=>release=ok),x=setup(vi.fn(()=>tracking)),started=x.session.start(true);await vi.waitFor(()=>expect(x.ready).toHaveBeenCalled());expect(x.reports.at(-1)).toMatchObject({camera:'READY',tracking:'LOADING'});release();await started;expect(x.reports.at(-1)).toMatchObject({camera:'READY',tracking:'READY'})});
  it('keeps the camera active when tracking initialization fails',async()=>{const x=setup(vi.fn(async()=>{throw new Error('model unavailable')}));await x.session.start(true);expect(x.session.active).toBe(true);expect(x.video.srcObject).not.toBeNull();expect(x.reports.at(-1)).toMatchObject({camera:'READY',tracking:'ERROR',message:'model unavailable'})});
  it('reports acquisition failure and prevents duplicate pending requests',async()=>{let reject!:(_:unknown)=>void;const pending=new Promise<MediaStream>((_,no)=>reject=no),request=vi.fn(()=>pending),x=setup(vi.fn(),request);const a=x.session.start(true),b=x.session.start(true);expect(a).toBe(b);expect(request).toHaveBeenCalledTimes(1);reject(new Error('permission denied'));await a;expect(x.reports.at(-1)).toMatchObject({camera:'ERROR',message:'permission denied'})});
  it('stops tracks and switches with a fresh stream',async()=>{const firstStop=vi.fn(),secondStop=vi.fn(),request=vi.fn().mockResolvedValueOnce({getTracks:()=>[{stop:firstStop}]}).mockResolvedValueOnce({getTracks:()=>[{stop:secondStop}]}),x=setup(vi.fn(async()=>{}),request);await x.session.start(true);await x.session.switchCamera(false);expect(firstStop).toHaveBeenCalledOnce();expect(request).toHaveBeenCalledTimes(2);x.session.stop();expect(secondStop).toHaveBeenCalledOnce();expect(x.video.srcObject).toBeNull()});
});
